name: CPack

on:
  push:
    tags:
      - "*.*.*"

jobs: 
  build_packages_Linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for tag operations

    - name: Configure Solver
      run: cmake -B ${{github.workspace}}/.build -D PRINT_VERSION=${{ github.ref_name }}

    - name: Build Solver
      run: cmake --build ${{github.workspace}}/.build

    - name: Build packages
      run: |
        cmake --build ${{github.workspace}}/.build --target package
        cmake --build ${{github.workspace}}/.build --target package_source

    - name: Verify artifacts
      run: ls -la ${{github.workspace}}/.build/*.deb ${{github.workspace}}/.build/*.tar.gz ${{github.workspace}}/.build/*.zip

    - name: Create or Update Release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: ".build/*.deb,.build/*.tar.gz,.build/*.zip"
        tag: ${{ github.ref_name }}
        update: true  # KEY FIX: Update existing release
        replace_artifacts: true  # Replace existing assets
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: solver-packages
        path: ${{github.workspace}}/.build/*.{deb,tar.gz,zip}
